# Generated by Django 4.2.26 on 2025-11-15 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalibrationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calibration_date", models.DateField()),
                ("next_calibration_date", models.DateField()),
                ("standards_used", models.TextField()),
                ("results", models.TextField()),
                ("passed", models.BooleanField(default=True)),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="calibration_certificates/%Y/%m/",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "calibration_records",
                "ordering": ["-calibration_date"],
            },
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("model", models.CharField(max_length=200)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("manufacturer", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("maintenance", "Under Maintenance"),
                            ("calibration", "Calibration Needed"),
                            ("offline", "Offline"),
                        ],
                        default="operational",
                        max_length=50,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("last_calibration_date", models.DateField(blank=True, null=True)),
                ("next_calibration_date", models.DateField(blank=True, null=True)),
                (
                    "calibration_frequency",
                    models.IntegerField(
                        default=365, help_text="Days between calibrations"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "instruments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("preventive", "Preventive"),
                            ("corrective", "Corrective"),
                            ("emergency", "Emergency"),
                        ],
                        max_length=50,
                    ),
                ),
                ("maintenance_date", models.DateField()),
                ("description", models.TextField()),
                ("parts_replaced", models.TextField(blank=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "downtime_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="instruments.instrument",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_logs",
                "ordering": ["-maintenance_date"],
            },
        ),
    ]
