# Generated by Django 4.2.26 on 2025-11-15 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0002_source"),
        ("samples", "0005_sample_originating_lab_sample_processing_lab_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("instruments", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentBorrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrower_type",
                    models.CharField(
                        choices=[
                            ("internal_user", "Internal User"),
                            ("external_user", "External User"),
                            ("student", "Student"),
                            ("lecturer", "Lecturer"),
                            ("researcher", "Researcher"),
                            ("lab", "Laboratory"),
                            ("department", "Department"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "borrower_name",
                    models.CharField(
                        help_text="Name of person/department borrowing", max_length=200
                    ),
                ),
                ("borrower_email", models.EmailField(blank=True, max_length=254)),
                ("borrower_phone", models.CharField(blank=True, max_length=20)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("research", "Research"),
                            ("teaching", "Teaching/Lecture"),
                            ("demonstration", "Demonstration"),
                            ("training", "Training"),
                            ("testing", "Testing/Analysis"),
                            ("calibration", "Calibration"),
                            ("maintenance", "Maintenance"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "purpose_description",
                    models.TextField(help_text="Detailed description of intended use"),
                ),
                (
                    "location_of_use",
                    models.CharField(
                        help_text="Where the instrument will be used", max_length=200
                    ),
                ),
                ("requested_date", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_start_date",
                    models.DateTimeField(
                        help_text="When borrower needs the instrument"
                    ),
                ),
                (
                    "requested_end_date",
                    models.DateTimeField(
                        help_text="When borrower will return the instrument"
                    ),
                ),
                (
                    "actual_borrow_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When instrument was actually borrowed",
                        null=True,
                    ),
                ),
                (
                    "actual_return_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When instrument was actually returned",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("borrowed", "Currently Borrowed"),
                            ("returned", "Returned"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "condition_at_checkout",
                    models.TextField(
                        blank=True, help_text="Condition of instrument when borrowed"
                    ),
                ),
                (
                    "condition_at_return",
                    models.TextField(
                        blank=True, help_text="Condition of instrument when returned"
                    ),
                ),
                (
                    "accessories_borrowed",
                    models.TextField(
                        blank=True,
                        help_text="List of accessories borrowed with instrument",
                    ),
                ),
                ("special_instructions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_borrowings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "borrower_lab",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lab borrowing the instrument",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="borrowed_instruments",
                        to="labs.lab",
                    ),
                ),
                (
                    "borrower_person",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person from labs module",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="borrowed_instruments",
                        to="labs.person",
                    ),
                ),
                (
                    "borrower_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to user account if internal user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="borrowed_instruments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_borrowings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowing_records",
                        to="instruments.instrument",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sample to be analyzed (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instrument_borrowings",
                        to="samples.sample",
                    ),
                ),
            ],
            options={
                "db_table": "instrument_borrowings",
                "ordering": ["-requested_date"],
                "indexes": [
                    models.Index(
                        fields=["status", "requested_start_date"],
                        name="instrument__status_a35ca8_idx",
                    ),
                    models.Index(
                        fields=["instrument", "status"],
                        name="instrument__instrum_b1359d_idx",
                    ),
                ],
            },
        ),
    ]
