# Generated by Django 4.2.26 on 2025-11-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("in", "Stock In"),
                            ("out", "Stock Out"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.CharField(max_length=500)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "inventory_transactions",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="Reagent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("catalog_number", models.CharField(max_length=100, unique=True)),
                ("manufacturer", models.CharField(max_length=200)),
                ("lot_number", models.CharField(max_length=100)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=50)),
                (
                    "minimum_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("expiry_date", models.DateField()),
                ("storage_location", models.CharField(max_length=200)),
                ("hazard_class", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "reagents",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("item_code", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("unit", models.CharField(max_length=50)),
                ("minimum_quantity", models.IntegerField()),
                ("supplier", models.CharField(blank=True, max_length=200)),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "stock_items",
                "ordering": ["name"],
            },
        ),
    ]
