# Generated by Django 4.2.26 on 2025-11-15 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytransaction",
            name="total_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total cost for this transaction",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost per unit at time of transaction",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reagent",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
        migrations.AddField(
            model_name="reagent",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reagent",
            name="supplier",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="reagent",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost per unit",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "monthly_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "yearly_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cost_centers",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CostAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_cost",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of total cost allocated to this center",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_allocations",
                        to="inventory.costcenter",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_allocations",
                        to="inventory.inventorytransaction",
                    ),
                ),
            ],
            options={
                "db_table": "cost_allocations",
                "ordering": ["-created_at"],
            },
        ),
    ]
