# Generated by Django 4.2.26 on 2025-11-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_cost_management"),
        ("inventory", "0003_inventorytransaction_total_cost_and_more"),
    ]

    operations = []
