# Generated by Django 4.2.26 on 2025-11-15 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hematology", "Hematology"),
                            ("biochemistry", "Biochemistry"),
                            ("microbiology", "Microbiology"),
                            ("immunology", "Immunology"),
                            ("molecular", "Molecular Biology"),
                            ("pathology", "Pathology"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "turnaround_time",
                    models.IntegerField(help_text="Expected turnaround time in hours"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tests",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TestAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("waiting_review", "Waiting Review"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="assigned",
                        max_length=50,
                    ),
                ),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                ("started_date", models.DateTimeField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "test_assignments",
                "ordering": ["-assigned_date"],
            },
        ),
        migrations.CreateModel(
            name="TestParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "reference_range_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "reference_range_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "reference_range_text",
                    models.CharField(
                        blank=True,
                        help_text='Text reference range (e.g., "Negative", "Positive")',
                        max_length=200,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="tests.test",
                    ),
                ),
            ],
            options={
                "db_table": "test_parameters",
                "ordering": ["test", "order", "name"],
            },
        ),
    ]
