# Generated by Django 4.2.26 on 2025-11-15 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("samples", "0002_initial"),
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testassignment",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="testassignment",
            name="assigned_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="testassignment",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_assignments",
                to="samples.sample",
            ),
        ),
        migrations.AddField(
            model_name="testassignment",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tests.test"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testassignment",
            unique_together={("sample", "test")},
        ),
    ]
