# Generated by Django 4.2.26 on 2025-11-15 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_inventorytransaction_total_cost_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tests", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="billable_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount charged to client",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="estimated_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated cost per test",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="testassignment",
            name="actual_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Actual cost incurred for this test",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="testassignment",
            name="deadline",
            field=models.DateTimeField(
                blank=True, help_text="Hard deadline for test completion", null=True
            ),
        ),
        migrations.AddField(
            model_name="testassignment",
            name="expected_completion",
            field=models.DateTimeField(
                blank=True,
                help_text="Expected completion based on turnaround time",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ReagentUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_used",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Quantity of reagent used",
                        max_digits=10,
                    ),
                ),
                (
                    "unit_cost_at_usage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost per unit at time of usage",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total cost for this usage",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("used_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "reagent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_usages",
                        to="inventory.reagent",
                    ),
                ),
                (
                    "test_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reagent_usages",
                        to="tests.testassignment",
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reagent_usages",
                "ordering": ["-used_date"],
            },
        ),
    ]
