# Generated by Django 4.2.26 on 2025-11-15 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "sample_type",
                    models.CharField(
                        choices=[
                            ("blood", "Blood"),
                            ("urine", "Urine"),
                            ("tissue", "Tissue"),
                            ("water", "Water"),
                            ("soil", "Soil"),
                            ("food", "Food"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source/Customer/Patient", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="registered",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("received_date", models.DateField(auto_now_add=True)),
                ("received_time", models.TimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "samples",
                "ordering": ["-received_date", "-received_time"],
            },
        ),
        migrations.CreateModel(
            name="SampleAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="sample_attachments/%Y/%m/%d/")),
                ("filename", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="samples.sample",
                    ),
                ),
            ],
            options={
                "db_table": "sample_attachments",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
