# Generated by Django 4.2.26 on 2025-11-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="actual_completion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="completion_deadline",
            field=models.DateTimeField(
                blank=True, help_text="Hard deadline for completion", null=True
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="expected_completion_date",
            field=models.DateField(
                blank=True, help_text="Expected completion deadline", null=True
            ),
        ),
    ]
