# Generated by Django 4.2.26 on 2025-11-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0003_sample_actual_completion_date_and_more"),
        ("samples", "0003_time_management"),
    ]

    operations = []
