# Generated by Django 4.2.26 on 2025-11-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0002_source"),
        ("samples", "0004_merge_20251115_1217"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="originating_lab",
            field=models.ForeignKey(
                blank=True,
                help_text="Lab that originally sent this sample",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="originated_samples",
                to="labs.lab",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="processing_lab",
            field=models.ForeignKey(
                blank=True,
                help_text="Lab processing this sample",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processing_samples",
                to="labs.lab",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="source_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Sample source (Customer/Patient/Lab)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="samples",
                to="labs.source",
                verbose_name="Source Reference",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="source",
            field=models.CharField(
                blank=True, help_text="Source/Customer/Patient (Legacy)", max_length=200
            ),
        ),
    ]
