# Generated by Django 4.2.26 on 2025-11-15 12:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("patient", "Patient"),
                            ("external_lab", "External Laboratory"),
                            ("internal_lab", "Internal Laboratory"),
                            ("research_partner", "Research Partner"),
                            ("hospital", "Hospital"),
                            ("clinic", "Clinic"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name or organization name", max_length=200
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique identifier code", max_length=50, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "state_province",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="State/Province"
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "organization_name",
                    models.CharField(
                        blank=True,
                        help_text="Parent organization if applicable",
                        max_length=200,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=200)),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, help_text="For patient sources only", null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("U", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(
                        blank=True,
                        help_text="External patient ID",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "accreditation",
                    models.CharField(
                        blank=True,
                        help_text="CAP, CLIA, ISO certifications, etc.",
                        max_length=200,
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("contact_title", models.CharField(blank=True, max_length=100)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or special instructions"
                    ),
                ),
                ("billing_reference", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sources",
                        to="labs.person",
                    ),
                ),
                (
                    "lab_reference",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to internal lab if source is an internal laboratory",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_sources",
                        to="labs.lab",
                    ),
                ),
            ],
            options={
                "verbose_name": "Source",
                "verbose_name_plural": "Sources",
                "ordering": ["name", "code"],
                "indexes": [
                    models.Index(
                        fields=["source_type", "is_active"],
                        name="labs_source_source__9a9df8_idx",
                    ),
                    models.Index(fields=["code"], name="labs_source_code_eccf94_idx"),
                ],
            },
        ),
    ]
